version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: golf-parser-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  datadog-agent:
    image: datadog/agent:latest
    container_name: golf-parser-datadog
    environment:
      - DD_API_KEY=${DD_API_KEY:-your_api_key_here}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
      - DD_PROCESS_AGENT_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8126:8126"
    depends_on:
      - rabbitmq

  golf-parser:
    build: .
    container_name: golf-parser-app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin123
      - DD_AGENT_HOST=datadog-agent
      - DD_AGENT_PORT=8126
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      datadog-agent:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    # restart: unless-stopped

volumes:
  rabbitmq_data: 