version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: golf-parser-rabbitmq
    ports:
      - "15672:15672"  # Web UI
      - "5672:5672"    # AMQP
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - monitoring

  datadog-agent:
    image: datadog/agent:latest
    container_name: golf-parser-datadog
    environment:
      - DD_API_KEY=13a5d2dcdf89c3f17a4c10c9e4446e72
      - DD_SITE=datadoghq.eu
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_COLLECT_DOCKER_METRICS=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    ports:
      - "8125:8125/udp"  # DogStatsD
      - "8126:8126"      # APM (traces)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For container monitoring
    networks:
      - monitoring

  golf-parser:
    build: .
    container_name: golf-parser-app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin123
      - DD_AGENT_HOST=datadog-agent
      - DD_DOGSTATSD_PORT=8125
      - DD_ENV=development
      - DD_SERVICE=golf-parser
      - DD_VERSION=1.0.0
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      datadog-agent:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  rabbitmq_data: 

networks:
  monitoring: